### ISSUE TITLE
USER STORY <TITLE>

### ISSUE THREAD

**Issue by Meghanarajvinakota** [Meghanarajvinakota/love--running#4]
In order to **r to collect users feedback,** as an**an administrator**, I can **publish a poll.**

## **Acceptance criteria:**
- **The option should be provided as a check box**
- **The checkbox should be checked by default**
- **The option button should appear next to the submit button**

## **Tasks**
- [x] **Create a new field in the model to track the username**
- [ ] **Update controller function**
- [ ] **Update unit test scripts**
